### PR TITLE
Problem: Can not query walletconnect status (fix #257)

### LINKED ISSUE #214: Problem: AsyncTask could not work on SetupCallback
SetupCallback would setup functions that would run on rust runtime, AsycTask would not work on rust runtime.

### LINKED ISSUE #257: Problem: Can not query walletconnect status

### PR DESCRIPTION
**Pull request by damoncro**
Close:
- #257

Solutions:
- Add internal _session_info and remove const
- Add public function: GetWalletConnectSessionInfo

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/play-unreal-plugin/blob/main/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest main? 
- [ ] Have you checked your code compiles in Unreal Engine 4 and 5?
- [ ] Have you checked your basic code formatting and style is fine? ([using this Linter plugin](https://ue4-style-guide.readthedocs.io/en/latest/gettingstarted.html))
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the plugin version number and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/play-unreal-plugin/blob/main/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/play-unreal-plugin/blob/main/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/play-unreal-plugin/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

File: Source/CronosPlayUnreal/Public/PlayCppSdkActor.h [hunk 1]
```diff
@@ -208,7 +208,10 @@ class CRONOSPLAYUNREAL_API APlayCppSdkActor : public AActor {
   private:
     static ::com::crypto::game_sdk::WalletconnectClient *_coreClient;
 
-    static const APlayCppSdkActor *_sdk;
+    static APlayCppSdkActor *_sdk;
```
Comment (tomtau) [inline Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: why not const?

**Review by tomtau — COMMENTED** [review]
thread-safety is ok?

File: Source/CronosPlayUnreal/Public/PlayCppSdkActor.h (hunk 1 above)
Comment (damoncro) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: Because we need to change the internal status: https://github.com/cronos-labs/play-unreal-plugin/pull/258/files#diff-097b9056119eecdfb8e1f150f586de6b3ed6ef617853a734a6f0d94006274fa1R638

Comment (damoncro) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: const will compilation failure.

Comment (tomtau) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: how does it work with concurrent updates? or there are never concurrent updates?

**Comment by damoncro** [comment]
> thread-safety is ok?

It should be fine, without the AsynTask, OnReceiveWalletconnectSessionInfoDelegate function could be called in GameThread correctly (AysncTask and run it in GameThread is redundant).

File: Source/CronosPlayUnreal/Public/PlayCppSdkActor.h (hunk 1 above)
Comment (damoncro) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: It only updates when walletconnect status changes, aka, connecting, disconnected, connected, updated. One user one session, no concurrent updates.

**Comment by tomtau** [comment]
maybe ok, but for the UE concurrency better for @leejw51crypto to check

File: Source/CronosPlayUnreal/Public/PlayCppSdkActor.h (hunk 1 above)
Comment (leejw51crypto) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: race conditions can occur, because sendevent is called non unreal thread.

Comment (leejw51crypto) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: should use mutex or queue if modification is necessary

Comment (leejw51crypto) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: how about modifying inside async task?

Comment (leejw51crypto) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: also `sendevent` can be changed to other, because it's modifying state, not only send event

Comment (damoncro) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: As long as sendEvent is called by one thread, no concurrent occurs, at least it is only called in callback function at this moment.

But it is ok to modify it as a thread safe function. Maybe in another PR?

Comment (damoncro) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: See https://github.com/cronos-labs/play-unreal-plugin/issues/264

Comment (damoncro) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: Close #264, kept AsyncTask, AysncTask works but and changed the title for: https://github.com/cronos-labs/play-unreal-plugin/issues/214

Comment (damoncro) [reply Source/CronosPlayUnreal/Public/PlayCppSdkActor.h:211]: See https://github.com/cronos-labs/play-unreal-plugin/pull/258/files#diff-097b9056119eecdfb8e1f150f586de6b3ed6ef617853a734a6f0d94006274fa1R641 as well.

**Review by tomtau — APPROVED** [review]
ok, the potential concurrency issues may be revisited in a follow up PR

**Review by leejw51crypto — APPROVED** [review]
