### PR TITLE
Problem: Game Crash When disconnect walletconnect manually (fix #274)

### LINKED ISSUE #274: Problem: Game Crash When disconnect walletconnect manually
No stable ways to disconnect walletconnect without restarting the game.

### PR DESCRIPTION
**Pull request by damoncro**
Close:
- #274

Solutions:
- Call destroyCoreClient in ClearSession
- Set the sessionstate to StateInit

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/play-unreal-plugin/blob/main/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest main? 
- [ ] Have you checked your code compiles in Unreal Engine 4 and 5?
- [ ] Have you checked your basic code formatting and style is fine? ([using this Linter plugin](https://ue4-style-guide.readthedocs.io/en/latest/gettingstarted.html))
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the plugin version number and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/play-unreal-plugin/blob/main/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/play-unreal-plugin/blob/main/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/play-unreal-plugin/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Review by tomtau — APPROVED** [review]

File: Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp [hunk 1]
```diff
@@ -400,9 +401,14 @@ void APlayCppSdkActor::ClearSession(bool &success) {
     IFileManager &FileManager = IFileManager::Get();
     success =
         FileManager.Delete(*(FPaths::ProjectSavedDir() + "sessioninfo.json"));
-    _coreClient = NULL;
+    destroyCoreClient();
```
Comment (leejw51crypto) [inline Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp:404]: destroyCoreClient is called from DestroyClient?

File: Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp [hunk 2]
```diff
@@ -400,9 +401,14 @@ void APlayCppSdkActor::ClearSession(bool &success) {
...
     FWalletConnectEnsureSessionResult session_result;
     _session_result = session_result;
+    _session_info.sessionstate =
```
Comment (leejw51crypto) [inline Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp:407]: how about make other function , move these clean up code

File: Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp (hunk 1 above)
Comment (damoncro) [reply Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp:404]: This is called in `ClearSession` where will clear all sessions, including QR code request and all other related network requests. Without it, the pending network requests can not be cleared after calling `ClearSession`.

Comment (leejw51crypto) [reply Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp:404]: aha, i see

**Review by leejw51crypto — APPROVED** [review]
lgtm

File: Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp (hunk 2 above)
Comment (damoncro) [reply Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp:407]: ok

Comment (damoncro) [reply Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp]: done

File: Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp (hunk 1 above)
Comment (damoncro) [reply Source/CronosPlayUnreal/Private/PlayCppSdkActor.cpp:404]: destroyCoreClient can not destroy pending network requests...

**Comment by leejw51crypto** [comment]
sendEvent seems to be causing unexpected crash.
let's include this fix for v0.0.11 release

**Comment by damoncro** [comment]
It is difficult to address the `true` cleaning up in this PR, follow in another issue https://github.com/cronos-labs/play-unreal-plugin/issues/278

This PR is necessary for Disconnect feature https://github.com/cronos-labs/play-unreal-plugin/issues/278, please help merge.

**Comment by leejw51crypto** [comment]
crash seems not related to this pr.
merge first, then solve as another pr ?
