### PR TITLE
Problem: compiling not working on ue5 (fix #97)

### LINKED ISSUE #97: Problem: compiling not working on ue5
fix compile for ue5

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: support ue5
conditional compiling by major version

### CODE REVIEW

File: Source/CronosPlayUnreal/Private/PlayCppSdkBPLibrary.cpp [hunk 1]
```diff
@@ -170,11 +171,21 @@ UTexture2D *UPlayCppSdkBPLibrary::GenerateQrCode(FString string) {
...
   FMemory::Memcpy(data, pixels.GetData(), size * size * 4);
   texture->PlatformData->Mips[0].BulkData.Unlock();
+#else
+  UTexture2D *texture = UTexture2D::CreateTransient(
+      size, size, EPixelFormat::PF_B8G8R8A8, "QRCode");
+  void *data =
+      texture->GetPlatformData()->Mips[0].BulkData.Lock(LOCK_READ_WRITE);
+  FMemory::Memcpy(data, pixels.GetData(), size * size * 4);
+  texture->GetPlatformData()->Mips[0].BulkData.Unlock();
+#endif
```
Comment (tomtau) [inline Source/CronosPlayUnreal/Private/PlayCppSdkBPLibrary.cpp:188]: I'm trying to check the difference, and it seems only the last line is different:
```
texture->GetPlatformData()->Mips[0].BulkData.Unlock();
```
vs
```
texture->PlatformData->Mips[0].BulkData.Unlock();
 ```

if that's the case, ifdef can only be on the last line?

Comment (leejw51crypto) [reply Source/CronosPlayUnreal/Private/PlayCppSdkBPLibrary.cpp:188]: and this line
```
 void *data =
      texture->GetPlatformData()
   ```
   but line 182  is redundant, i'll fix

Comment (tomtau) [reply Source/CronosPlayUnreal/Private/PlayCppSdkBPLibrary.cpp:188]: oh, ok, L182/L176 are duplicate and can be moved up

**Review by tomtau — APPROVED** [review]
